# Programming Exercise: Robot Localization

#### Cancer Test Example
Let us apply Bayes' Rule to a Cancer Test Example which is a very common example in Statistic classes.
Suppose, there is a certain type of cancer which is extremely rare.

Let,
\begin{equation}
P(C) = 0.001
\end{equation}
In other words, $1$ in every $1000$ people has this cancer. Can you compute the probability of not having cancer?
\begin{equation}
P(\neg C) = ?
\end{equation}

The test for cancer is not $100\%$ accurate. Let us say, probability of the test being positive given someone has cancer is,
\begin{equation}
P(pos | C) = 0.8
\end{equation}
Can you compute the probability that the test is negative given someone has cancer?
\begin{equation}
P(neg | C) = ?
\end{equation}

Similarly, the probability of a test being positive given that someone has no cancer is $P(pos | \neg C) = 0.1$. Can you compute the probability that the test is negative given someone has no cancer?
\begin{equation}
P(neg | \neg C) = ?
\end{equation}

Can you compute the following?
\begin{equation}
P(C | pos) = ?
\end{equation}
Interpret the quantity you computed in words!

What we computed is very interesting. We computed probability of having cancer given the test results and how likely the disease is.

In [0]:
pnotc=0.999
pneggivenc=0.2
pneggivennotc=0.9

#Required probability
pcgivenpos=0.8*0.001/(0.8*0.001+0.1*0.999)

print(pcgivenpos)

0.007944389275074478


In [0]:
def init_distribution(n):
    p = []
    # Add your code here
    p = [ 1/n for i in range(n) ]
    # End your code here
    return p

In [0]:
init_distribution(5)

[0.2, 0.2, 0.2, 0.2, 0.2]

In [0]:
#Modify the code below so that the function sense, which 
#takes p and Z as inputs, will output the normalized 
#probability distribution, q, after multiplying the entries 
# in p according to the color in the corresponding cell in world,
# followed by normalization of the probability values
world=['green', 'red', 'red', 'green', 'green']
# p(bt,sr)=p(sr,bt)/(p(sr))
import numpy as np


def sense(p, Z):
    q = np.zeros((0))
    flag=0
    for i in range(len(p)):
        if(world[i]==Z):
          q=np.hstack([q,p[i]*0.75])
        else:
          q=np.hstack([q,p[i]*0.25])
    a=q.sum()
    for i in range(len(q)):
      q[i]=q[i]/a
    return q
# sense(p, 'red')
p=[0.2,0.2,0.2,0.2,0.2]
sense(p,'red')

array([0.11111111, 0.33333333, 0.33333333, 0.11111111, 0.11111111])

In [0]:
p=[0.2, 0.2, 0.2, 0.2, 0.2]
world=['green', 'red', 'red', 'green', 'green']
measurements = ['red', 'green']

# Add your code here
for z in measurements:
  p=sense(p,z)
  print(p)
# End your code here


[0.11111111 0.33333333 0.33333333 0.11111111 0.11111111]
[0.2 0.2 0.2 0.2 0.2]


In [0]:
#Program a function that returns a new distribution 
#q, shifted to the right by U units. If U=0, q should 
#be the same as p.

def move(p, U):
  
    # ADD CODE HERE
    
    q=np.roll(np.array(p),U)
    # END CODE HERE
    return q

move([0.11, 0.33, 0.33, 0.11, 0.11], 1)




array([0.11, 0.11, 0.33, 0.33, 0.11])

In [0]:
def inmove(p,U):
  return move(p,U-1)*0.1 + move(p,U)*0.8 + move(p,U+1)*0.1
  # q=[0,0,0,0,0]
  # for i in range(len(q)):
  #   q[i]=0.1*p[(i-U+1)%len(q)] + 0.8*p[(i-U)%len(q)] + 0.1*p[(i-U-1)%len(q)]

  return q
inmove([0, 1.0, 0, 0, 0], 2)

#[0,1,0.1,0,0]
#[0,1,0.2,1,0.1]
#[0.1,1,0.2,1.1,1.1]

array([0. , 0. , 0.1, 0.8, 0.1])

In [0]:
def inmove(p,U):
  return move(p,U-1)*0.1 + move(p,U)*0.8 + move(p,U+1)*0.1
  # q=[0,0,0,0,0]
  # for i in range(len(q)):
  #   q[i]=0.1*p[(i-U+1)%len(q)] + 0.8*p[(i-U)%len(q)] + 0.1*p[(i-U-1)%len(q)]

  return q

def move_step(p,steps):
  move1=p
  for i in range(steps):
    move1=inmove(move1,1)
  # print(move1)
  return move1
print(move_step([0,1,0,0,0],100))

[0.20000004 0.20000014 0.20000004 0.19999989 0.19999989]


In [0]:
#Putting everything together
move1=[0.2,0.2,0.2,0.2,0.2]
measurements=['red','green']
motions=[1,1]

p=[0.2,0.2,0.2,0.2,0.2]
# print(sense(p,'red'))


for i in range(2):
  move1=sense(move1,measurements[i])
  print(move1)
  move1=inmove(move1,motions[i])
  print(move1)

[0.11111111 0.33333333 0.33333333 0.11111111 0.11111111]
[0.11111111 0.13333333 0.31111111 0.31111111 0.13333333]
[0.15789474 0.06315789 0.14736842 0.44210526 0.18947368]
[0.21157895 0.15157895 0.08105263 0.16842105 0.38736842]
